In [2]:
import pandas as pd
a = pd.read_csv('practice.csv')
a

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No

# 2.	create numerical and categorical columns list

In [10]:
print(f'column list is :  {a.columns}')

column list is :  Index(['MSSubClass', 'MSZoning', 'LotArea', 'LotShape', 'LotConfig',
       'LandSlope', 'OverallQual', 'YearBuilt', 'MasVnrArea', 'ExterQual',
       'BsmtExposure'],
      dtype='object')

# 3.	display size of the data-frame

In [7]:
print(f'Size of the data frame is {a.size} bytes')

Size of the data frame is 330 bytes

# 4.	rename column MSSubClass -> SubClass, MSZoning -> Zones

In [21]:
# a.rename(columns = {'MSSubClass':'SubClass','MSZoning':'Zones'},inplace = True)
# a

# 5.	display distinct values for Zoning, LotShape, LotConfig

In [27]:
# (a[['Zones','LotArea','LotConfig']])

# 6.	display count of distinct values for Zoning, LotShape, LotConfig

In [38]:
a[['Zones','LotArea','LotConfig']]

   Zones  LotArea LotConfig
0     RL     8450    Inside
1     RL     9600       FR2
2     RL    11250    Inside
3     RL     9550    Corner
4     RL    14260       FR2
5     RL    14115    Inside
6     RL    10084    Inside
7     RL    10382    Corner
8     RM     6120    Inside
9     RL     7420    Corner
10    RL    11200    Inside
11    RL    11924    Inside
12    RL    12968    Inside
13    RL    10652    Inside
14    RL    10920    Corner
15    RM     6120    Corner
16    RL    11241   CulDSac
17    RL    10791    Inside
18    RL    13695    Inside
19    RL     7560    Inside
20    RL    14215    Corner
21    RM     7449    Inside
22    RL     9742    Inside
23    RM     4224    Inside
24    RL     8246    Inside
25    RL    14230    Corner
26    RL     7200    Corner
27    RL    11478    Inside
28    RL    16321   CulDSac
29    RM     6324    Inside

# 7.	max, min of column YearBuilt

In [54]:
print("Max value of column yearbuilt is", a['YearBuilt'].max())
print("Max value of column yearbuilt is", a['YearBuilt'].min())

Max value of column yearbuilt is 2007
Max value of column yearbuilt is 1915

# 8.	create a new column “year_diff’. This will be holding difference of current year and YearBuilt

In [61]:
# a['Current year'] = 2020
# a['year_diff'] =  a['Current year'] - a['YearBuilt']
# a

# 9.	display distinct MSZoning for each OverallQual

In [64]:
a.Zones.unique()

array(['RL', 'RM'], dtype=object)

# 10.	What is the maximum LotArea where  BsmtExposure = Mn?

In [72]:
print('the maximum LotArea where  BsmtExposure = Mn is : ',a[a.BsmtExposure == 'Mn'].LotArea.max())

the maximum LotArea where  BsmtExposure = Mn is :  11250

# 11.	Sort dataframe based on following columns and orders: MSSubClass; ascending, YearBuilt; descending

In [74]:
a.sort_values( by = ['SubClass','YearBuilt'], ascending = [True,False])

,SubClass,Zones,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,Current year,year_diff
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,2020,13
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,2020,13
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,2020,14
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,2020,16
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,2020,16
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,2020,18
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,2020,44
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,2020,50
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,2020,52
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,2020,55
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,2020,58
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,2020,60
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,2020,62
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,2020,63
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,2020,69
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,2020,93
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,2020,90
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,2020,91
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,2020,27
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,2020,89
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,2020,15
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,2020,15
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,2020,17
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,2020,19
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,2020,20
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,2020,47
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,2020,105
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN,2020,53
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,2020,44
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,2020,81

# 12.	What is average OverallQual.

In [77]:
print('Average value of OverallQual', a.OverallQual.mean())

Average value of OverallQual 6.3

# 13.	convert column ‘YearBuilt’ into date type.

In [15]:
import pandas as pd
c = pd.read_csv('practice.csv')
c['val'] = c.YearBuilt.dtypes
c

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,val
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,int64
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,int64
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,int64
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,int64
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,int64
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,int64
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,int64
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,int64
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,int64
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,int64
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,int64
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,int64
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,int64
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,int64
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,int64
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,int64
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,int64
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN,int64
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,int64
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,int64
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,int64
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,int64
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,int64
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,int64
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,int64
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,int64
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,int64
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,int64
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,int64
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,int64

# 14.	Group by YearBuilt and find maximum OverallQal

In [19]:
c.groupby('YearBuilt')['OverallQual'].max().reset_index()

    YearBuilt  OverallQual
0        1915            7
1        1927            4
2        1929            7
3        1930            7
4        1931            7
5        1939            5
6        1951            5
7        1957            5
8        1958            5
9        1960            6
10       1962            5
11       1965            5
12       1967            4
13       1968            5
14       1970            6
15       1973            7
16       1976            6
17       1993            5
18       2000            8
19       2001            7
20       2002            8
21       2003            7
22       2004            8
23       2005            9
24       2006            7
25       2007            8

# 15.	Load the practice.csv again with MSSubClass as new index

In [21]:
c.index

RangeIndex(start=0, stop=30, step=1)

# 16.	Convert LotArea as numpy array

In [30]:
import numpy as np
d =[]
for i in c['LotArea']:
    d.append(i)
print(d, end = '\n\n')
print(np.array(d))

[8450, 9600, 11250, 9550, 14260, 14115, 10084, 10382, 6120, 7420, 11200, 11924, 12968, 10652, 10920, 6120, 11241, 10791, 13695, 7560, 14215, 7449, 9742, 4224, 8246, 14230, 7200, 11478, 16321, 6324]

[ 8450  9600 11250  9550 14260 14115 10084 10382  6120  7420 11200 11924
 12968 10652 10920  6120 11241 10791 13695  7560 14215  7449  9742  4224
  8246 14230  7200 11478 16321  6324]

# 17.	In column MasVnrArea replace 0 with -1

In [46]:
# c.MasVnrArea.unique()
c['MasVnrAreac'] =c[['MasVnrArea']].replace(to_replace = 0,value =-1)
c

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,val,MasVnrAreac
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,int64,196
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,int64,-1
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,int64,162
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,int64,-1
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,int64,350
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,int64,-1
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,int64,186
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,int64,240
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,int64,-1
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,int64,-1
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,int64,-1
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,int64,286
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,int64,-1
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,int64,306
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,int64,212
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,int64,-1
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,int64,180
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN,int64,-1
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,int64,-1
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,int64,-1
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,int64,380
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,int64,-1
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,int64,281
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,int64,-1
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,int64,-1
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,int64,640
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,int64,-1
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,int64,200
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,int64,-1
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,int64,-1