In [5]:
import pandas as pd
a = pd.read_csv("netflix.csv")
a[(a.release_year == 2019) & (a.type == 'TV Show')]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
34,80221550,TV Show,Archibald's Next Big Thing,NaN,"Tony Hale, Rosamund Pike, Jordan Fisher, Chels...",NaN,2019,TV-Y7,1 Season,"Kids' TV, TV Comedies"
39,80178151,TV Show,The Spy,NaN,"Sacha Baron Cohen, Noah Emmerich, Hadar Ratzon...",France,2019,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers"
99,80225885,TV Show,Bard of Blood,NaN,"Emraan Hashmi, Viineet Kumar, Sobhita Dhulipal...",India,2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,..."
101,80218107,TV Show,Dragons: Rescue Riders,NaN,"Nicolas Cantu, Brennley Brown, Zach Callison, ...",NaN,2019,TV-Y,1 Season,"Kids' TV, TV Comedies"
103,80220715,TV Show,Skylines,NaN,"Edin Hasanovic, Peri Baumeister, Murathan Musl...",NaN,2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas"
...,...,...,...,...,...,...,...,...,...,...
6198,80189829,TV Show,The Protector,NaN,"Çağatay Ulusoy, Ayça Ayşin Turan, Hazar Ergüçl...",Turkey,2019,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
6204,80091341,TV Show,Cuckoo,NaN,"Andy Samberg, Taylor Lautner, Greg Davies, Hel...",United Kingdom,2019,TV-14,5 Seasons,"British TV Shows, International TV Shows, TV C..."
6206,80173174,TV Show,Samantha!,NaN,"Emmanuelle Araújo, Douglas Silva, Sabrina Nona...",Brazil,2019,TV-MA,2 Seasons,"International TV Shows, TV Comedies"
6215,80066227,TV Show,Crazy Ex-Girlfriend,NaN,"Rachel Bloom, Vincent Rodriguez III, Santino F...",United States,2019,TV-14,4 Seasons,"Romantic TV Shows, TV Comedies"
6219,80186475,TV Show,Pokémon the Series,NaN,"Sarah Natochenny, Laurie Hymes, Jessica Paquet...",Japan,2019,TV-Y7-FV,2 Seasons,"Anime Series, Kids' TV"

In [16]:
a[(a.type == 'Movie') & (a.release_year.isin([2018,2019,2020])) & (a.country == 'India')]['rating'].unique()

array(['TV-MA', 'TV-14', 'TV-PG', 'TV-Y7', 'TV-G', 'PG-13', 'TV-Y7-FV'],
      dtype=object)

In [19]:
a[a.country == 'United States']

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,2017,TV-MA,1 Season,"Docuseries, Science & Nature TV"
20,80060297,Movie,Manhattan Romance,Tom O'Brien,"Tom O'Brien, Katherine Waterston, Caitlin Fitz...",United States,2014,TV-14,98 min,"Comedies, Independent Movies, Romantic Movies"
...,...,...,...,...,...,...,...,...,...,...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies"
6226,70243132,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh..."
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies"

In [22]:
a[(a.rating == 'R') & (a.release_year == 2019)]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
87,80200087,Movie,Domino,Brian De Palma,"Nikolaj Coster-Waldau, Carice van Houten, Eriq...","Denmark, France, Italy, Belgium, Netherlands",2019,R,89 min,"International Movies, Thrillers"
125,81053953,Movie,Inside Man: Most Wanted,Michael J. Bassett,"Aml Ameen, Rhea Seehorn, Roxanne McKee, Urs Re...",United States,2019,R,106 min,Action & Adventure
529,80182014,Movie,Dolemite Is My Name,Craig Brewer,"Eddie Murphy, Wesley Snipes, Keegan-Michael Ke...",United States,2019,R,118 min,"Comedies, Dramas"
654,80994011,Movie,The Laundromat,Steven Soderbergh,"Meryl Streep, Gary Oldman, Antonio Banderas, S...",United States,2019,R,96 min,"Comedies, Dramas"
1038,81053961,Movie,Undercover Brother 2,Leslie Small,"Michael Jai White, Vince Swann, Barry Bostwick...",United States,2019,R,85 min,Comedies
1100,80175798,Movie,The Irishman,Martin Scorsese,"Robert De Niro, Al Pacino, Joe Pesci, Harvey K...",United States,2019,R,209 min,Dramas
1264,80244457,Movie,Earthquake Bird,Wash Westmoreland,"Alicia Vikander, Riley Keough, Naoki Kobayashi...",United States,2019,R,107 min,"Dramas, Romantic Movies"
1419,80182016,Movie,The King,David Michôd,"Timothée Chalamet, Joel Edgerton, Robert Patti...",NaN,2019,R,141 min,Dramas
1625,81028570,Movie,"Extremely Wicked, Shockingly Evil and Vile",Joe Berlinger,"Zac Efron, Lily Collins, Kaya Scodelario, Jeff...",United States,2019,R,110 min,"Dramas, Independent Movies"
1773,81053958,Movie,Backdraft 2,Gonzalo López-Gallego,"Joe Anderson, William Baldwin, Donald Sutherla...",United States,2019,R,102 min,"Action & Adventure, Dramas"
1807,80194950,Movie,Wine Country,Amy Poehler,"Amy Poehler, Maya Rudolph, Ana Gasteyer, Rache...",United States,2019,R,104 min,Comedies
2051,80200571,Movie,The Highwaymen,John Lee Hancock,"Kevin Costner, Woody Harrelson, Kathy Bates, J...",United States,2019,R,132 min,Dramas
2239,80192187,Movie,Triple Frontier,J.C. Chandor,"Ben Affleck, Oscar Isaac, Charlie Hunnam, Pedr...",United States,2019,R,126 min,Action & Adventure
2431,80202465,Movie,"Berlin, I Love You",NaN,NaN,Germany,2019,R,120 min,"Dramas, International Movies, Romantic Movies"
2457,80996787,Movie,Everybody Knows,Asghar Farhadi,"Penélope Cruz, Javier Bardem, Ricardo Darín, E...","Spain, France, Italy",2019,R,133 min,"Dramas, International Movies, Thrillers"
3381,81144867,Movie,Saving Zoë,Jeffrey G. Hunt,"Laura Marano, Vanessa Marano, Christopher Tava...",United States,2019,R,95 min,Dramas
4042,80199689,Movie,Velvet Buzzsaw,Dan Gilroy,"Jake Gyllenhaal, Rene Russo, Zawe Ashton, Toni...",United States,2019,R,113 min,"Dramas, Thrillers"
4132,80223779,Movie,Marriage Story,Noah Baumbach,"Scarlett Johansson, Adam Driver, Laura Dern, A...","United States, United Kingdom",2019,R,137 min,Dramas
4351,81164603,Movie,Doom: Annihilation,Tony Giglio,"Amy Manson, Dominic Mafham, Luke Allen-Gale, J...",United States,2019,R,97 min,"Action & Adventure, Horror Movies, Sci-Fi & Fa..."
4354,81164636,Movie,Jarhead: Law of Return,Don Michael Paul,"Amaury Nolasco, Devon Sawa, Robert Patrick, Je...","Israel, United States",2019,R,103 min,"Action & Adventure, Dramas"
4377,81014479,Movie,Jacob's Ladder,David M. Rosenthal,"Michael Ealy, Jesse Williams, Nicole Beharie, ...",United States,2019,R,90 min,Thrillers
4579,81001887,Movie,6 Underground,Michael Bay,"Ryan Reynolds, Mélanie Laurent, Corey Hawkins,...",United States,2019,R,129 min,"Action & Adventure, Dramas"
4905,80211623,Movie,Otherhood,NaN,NaN,"United Kingdom, United States",2019,R,101 min,Comedies
5363,80202920,Movie,Someone Great,Jennifer Kaytin Robinson,"Gina Rodriguez, Brittany Snow, DeWanda Wise, L...",United States,2019,R,92 min,"Comedies, Romantic Movies"

In [24]:
a.drop(columns = 'show_id')

,type,title,director,cast,country,release_year,rating,duration,listed_in
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies
...,...,...,...,...,...,...,...,...,...
6229,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies
6231,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies
6232,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas"
6233,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies"

In [25]:
a.duration.unique()

array(['90 min', '94 min', '1 Season', '99 min', '110 min', '60 min',
       '78 min', '95 min', '58 min', '62 min', '65 min', '61 min',
       '135 min', '98 min', '96 min', '79 min', '113 min', '80 min',
       '77 min', '112 min', '106 min', '102 min', '114 min', '125 min',
       '142 min', '133 min', '100 min', '86 min', '146 min', '10 min',
       '122 min', '126 min', '116 min', '130 min', '70 min', '128 min',
       '88 min', '108 min', '93 min', '64 min', '107 min', '92 min',
       '111 min', '103 min', '40 min', '85 min', '72 min', '45 min',
       '89 min', '24 min', '127 min', '163 min', '117 min', '42 min',
       '104 min', '75 min', '82 min', '38 min', '97 min', '81 min',
       '91 min', '152 min', '87 min', '121 min', '101 min', '119 min',
       '83 min', '182 min', '124 min', '63 min', '139 min', '171 min',
       '84 min', '69 min', '76 min', '41 min', '153 min', '141 min',
       '52 min', '137 min', '132 min', '157 min', '109 min', '105 min',
       '25 min', '71 min', '123 min', '67 min', '140 min', '138 min',
       '149 min', '47 min', '68 min', '148 min', '54 min', '151 min',
       '155 min', '162 min', '28 min', '160 min', '29 min', '57 min',
       '46 min', '73 min', '74 min', '118 min', '66 min', '14 min',
       '20 min', '115 min', '48 min', '168 min', '144 min', '161 min',
       '55 min', '56 min', '51 min', '50 min', '23 min', '205 min',
       '190 min', '131 min', '22 min', '59 min', '150 min', '159 min',
       '145 min', '158 min', '143 min', '154 min', '147 min', '129 min',
       '214 min', '136 min', '134 min', '44 min', '156 min', '30 min',
       '120 min', '209 min', '166 min', '200 min', '185 min', '36 min',
       '11 min', '53 min', '165 min', '164 min', '19 min', '177 min',
       '32 min', '18 min', '170 min', '187 min', '173 min', '12 min',
       '3 min', '176 min', '15 min', '49 min', '26 min', '37 min',
       '189 min', '201 min', '179 min', '191 min', '193 min', '192 min',
       '43 min', '172 min', '224 min', '27 min', '181 min', '178 min',
       '228 min', '34 min', '312 min', '174 min', '169 min', '35 min',
       '31 min', '180 min', '196 min', '167 min', '33 min', '203 min',
       '195 min', '2 Seasons', '5 Seasons', '3 Seasons', '7 Seasons',
       '4 Seasons', '8 Seasons', '6 Seasons', '9 Seasons', '14 Seasons',
       '10 Seasons', '12 Seasons', '15 Seasons', '11 Seasons',
       '13 Seasons'], dtype=object)

In [32]:
a['duration_min'] = a.duration.apply(lambda x : x.split()[0])
a

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,duration_min
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies",90
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy,94
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV,1
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV,1
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies,99
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...",13
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies,4
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies,60
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas",2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",10

In [33]:
text = 'geeks for geeks'

# Splits at space 
print(text.split()) 

word = 'geeks, for, geeks'

# Splits at ',' 
print(word.split(',')) 

word = 'geeks:for:geeks'

# Splitting at ':' 
print(word.split(':')) 

word = 'CatBatSatFatOr'

# Splitting at 3 
print([word[i:i+3] for i in range(0, len(word), 3)])

['geeks', 'for', 'geeks']
['geeks', ' for', ' geeks']
['geeks', 'for', 'geeks']
['Cat', 'Bat', 'Sat', 'Fat', 'Or']

In [34]:
a.duration.unique()

array(['90 min', '94 min', '1 Season', '99 min', '110 min', '60 min',
       '78 min', '95 min', '58 min', '62 min', '65 min', '61 min',
       '135 min', '98 min', '96 min', '79 min', '113 min', '80 min',
       '77 min', '112 min', '106 min', '102 min', '114 min', '125 min',
       '142 min', '133 min', '100 min', '86 min', '146 min', '10 min',
       '122 min', '126 min', '116 min', '130 min', '70 min', '128 min',
       '88 min', '108 min', '93 min', '64 min', '107 min', '92 min',
       '111 min', '103 min', '40 min', '85 min', '72 min', '45 min',
       '89 min', '24 min', '127 min', '163 min', '117 min', '42 min',
       '104 min', '75 min', '82 min', '38 min', '97 min', '81 min',
       '91 min', '152 min', '87 min', '121 min', '101 min', '119 min',
       '83 min', '182 min', '124 min', '63 min', '139 min', '171 min',
       '84 min', '69 min', '76 min', '41 min', '153 min', '141 min',
       '52 min', '137 min', '132 min', '157 min', '109 min', '105 min',
       '25 min', '71 min', '123 min', '67 min', '140 min', '138 min',
       '149 min', '47 min', '68 min', '148 min', '54 min', '151 min',
       '155 min', '162 min', '28 min', '160 min', '29 min', '57 min',
       '46 min', '73 min', '74 min', '118 min', '66 min', '14 min',
       '20 min', '115 min', '48 min', '168 min', '144 min', '161 min',
       '55 min', '56 min', '51 min', '50 min', '23 min', '205 min',
       '190 min', '131 min', '22 min', '59 min', '150 min', '159 min',
       '145 min', '158 min', '143 min', '154 min', '147 min', '129 min',
       '214 min', '136 min', '134 min', '44 min', '156 min', '30 min',
       '120 min', '209 min', '166 min', '200 min', '185 min', '36 min',
       '11 min', '53 min', '165 min', '164 min', '19 min', '177 min',
       '32 min', '18 min', '170 min', '187 min', '173 min', '12 min',
       '3 min', '176 min', '15 min', '49 min', '26 min', '37 min',
       '189 min', '201 min', '179 min', '191 min', '193 min', '192 min',
       '43 min', '172 min', '224 min', '27 min', '181 min', '178 min',
       '228 min', '34 min', '312 min', '174 min', '169 min', '35 min',
       '31 min', '180 min', '196 min', '167 min', '33 min', '203 min',
       '195 min', '2 Seasons', '5 Seasons', '3 Seasons', '7 Seasons',
       '4 Seasons', '8 Seasons', '6 Seasons', '9 Seasons', '14 Seasons',
       '10 Seasons', '12 Seasons', '15 Seasons', '11 Seasons',
       '13 Seasons'], dtype=object)

In [35]:
a

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,duration_min
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies",90
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy,94
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV,1
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV,1
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies,99
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...",13
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies,4
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies,60
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas",2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",10

In [36]:
b = a.copy()
b

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,duration_min
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies",90
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy,94
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV,1
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV,1
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies,99
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...",13
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies,4
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies,60
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas",2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",10

In [2]:
a[6232] = 'siva'
a

NameError: name 'a' is not defined

In [39]:
b[b.country == 'India'].country.unique()

array(['India'], dtype=object)

In [ ]:
if we give 'india' as filtering urgument for the column 'country'. It is not taken our urgument , 
which is presenting with
some other urguments. example (United States, India, South Korea, China) show id 81145628